# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SWoPP2018プログラム
email: SWoPP2018組織委員会 <swopp17-secretary _at_ googlegroups.com>
description: 2018年並列／分散／協調処理に関する『熊本』サマー・ワークショップ (SWoPP2018)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://swopp.github.io" # the base hostname & protocol for your site
twitter_username: swoppweb
github_username:  swopp

# Build settings
markdown: kramdown
